### ISSUE TITLE
Enchanting table deletes lapis when exiting menu without removing the lapis

### ISSUE THREAD

**Issue by TaiyoFurea** [GreenJAB/fixed-minecraft#23]
Title. 

I opened the table, put in a book and lapis, realized you can't enchant books in this mod, took the book out, closed the menu, and my lapis was gone. It wasn't there when I reopened the table and it wasn't in my inventory, floor, or any nearby chests.

**Comment by GreenJAB** [comment]
Interesting. I have just tried this myself but it all worked fine. I don't touch the 'On Close' part of the enchanting table code. Would you be able to try again with a little bit of lapis to confirm? Otherwise do you have any other mods or anything that could be conlifcting?

**Comment by TaiyoFurea** [comment]
Alright, I figured out the specifics. if you put a book and lapis in the table and then click where the enchantment options *would* be, upon removing the lapis it deletes it

**Comment by GreenJAB** [comment]
Thanks. This will be fixed in the next release.
